/* ============= NFT catalog ============= */

const NFT_LIBRARY = [
  {
    id: 'NFT-0001',
    name: 'Stardust Crown',
    art: 'starCrown',
    slot: 'head',
    fabric: 'Silk',
    fit: 'Structured',
    finish: 'Metallic threading',
    color: 'Gradients',
    mint: 'Legendary',
    rarity: 'Legendary',
    serial: '#0014 / 100',
    lore: 'Forged from a meteor that grazed our atmosphere in 2019. The original wearer is unknown.',
    pointsBonus: 250,
    owned: true,
  },
  {
    id: 'NFT-0002',
    name: 'Cloudbunny Hood',
    art: 'bunnyEars',
    slot: 'head',
    fabric: 'Cotton',
    fit: 'Oversized',
    finish: 'Washed',
    color: 'Solid (Pink)',
    mint: 'Mint',
    rarity: 'Rare',
    serial: '#0421 / 5,000',
    lore: 'Cosy, fluffy, slightly haunted by static. Squeezable in both realms.',
    pointsBonus: 100,
    owned: true,
  },
  {
    id: 'NFT-0003',
    name: 'Voltbloom Helm',
    art: 'thunderHelm',
    slot: 'head',
    fabric: 'Techwear',
    fit: 'Slim',
    finish: 'Reflective',
    color: 'Color-shifting',
    mint: 'Worn',
    rarity: 'Epic',
    serial: '#0089 / 500',
    lore: 'Outfit pulled from a cancelled lookbook. Hum of voltage when worn for too long.',
    pointsBonus: 175,
    owned: true,
  },
  {
    id: 'NFT-0004',
    name: 'Ember Tiara',
    art: 'flameTiara',
    slot: 'head',
    fabric: 'Leather',
    fit: 'Cropped',
    finish: 'Distressed',
    color: 'Solid (Black)',
    mint: 'Vintage',
    rarity: 'Epic',
    serial: '#0007 / 250',
    lore: 'A Y2K tour relic — flame motif borrowed by half the city.',
    pointsBonus: 150,
    owned: false,
  },
  {
    id: 'NFT-0005',
    name: 'Nimbus Hoodie',
    art: 'cloudHoodie',
    slot: 'outfit',
    fabric: 'Cotton',
    fit: 'Oversized',
    finish: 'Matte',
    color: 'Solid (Sky)',
    mint: 'Mint',
    rarity: 'Common',
    serial: '#1240 / 10,000',
    lore: 'The starter hoodie. Beloved, pilled in all the right places.',
    pointsBonus: 100,
    owned: true,
  },
  {
    id: 'NFT-0006',
    name: 'Glitchcrop Top',
    art: 'cropPink',
    slot: 'outfit',
    fabric: 'Techwear',
    fit: 'Cropped',
    finish: 'Glossy',
    color: 'Pattern (Glitch)',
    mint: 'Mint',
    rarity: 'Rare',
    serial: '#0301 / 2,500',
    lore: 'Pixel-shifted threads cause a faint shimmer; wash separately.',
    pointsBonus: 100,
    owned: true,
  },
  {
    id: 'NFT-0007',
    name: 'Ember Carapace',
    art: 'emberJacket',
    slot: 'outfit',
    fabric: 'Leather',
    fit: 'Structured',
    finish: 'Distressed',
    color: 'Solid (Coral)',
    mint: 'Vintage',
    rarity: 'Legendary',
    serial: '#0003 / 50',
    lore: 'Each scale is hand-stamped by a former blacksmith named Pat.',
    pointsBonus: 250,
    owned: false,
  },
  {
    id: 'NFT-0008',
    name: 'Void Cloak',
    art: 'voidCloak',
    slot: 'outfit',
    fabric: 'Silk',
    fit: 'Oversized',
    finish: 'Reflective',
    color: 'Color-shifting',
    mint: 'Legendary',
    rarity: 'Legendary',
    serial: '#0001 / 25',
    lore: 'Embroidered with the names of stars that have already gone out.',
    pointsBonus: 250,
    owned: false,
  },
  {
    id: 'NFT-0009',
    name: 'Frostspire Staff',
    art: 'iceStaff',
    slot: 'item',
    fabric: 'Techwear',
    fit: 'Slim',
    finish: 'Reflective',
    color: 'Solid (Ice)',
    mint: 'Mint',
    rarity: 'Rare',
    serial: '#0822 / 3,000',
    lore: 'Accessory only. Does not actually freeze water. Looks rad.',
    pointsBonus: 100,
    owned: true,
  },
  {
    id: 'NFT-0010',
    name: 'Stargaze Scepter',
    art: 'starWand',
    slot: 'item',
    fabric: 'Silk',
    fit: 'Structured',
    finish: 'Metallic threading',
    color: 'Gradients',
    mint: 'Worn',
    rarity: 'Epic',
    serial: '#0066 / 750',
    lore: 'Heavier than it looks. Pairs well with anything pastel.',
    pointsBonus: 175,
    owned: true,
  },
  {
    id: 'NFT-0011',
    name: 'Ember Blade',
    art: 'emberBlade',
    slot: 'item',
    fabric: 'Denim',
    fit: 'Slim',
    finish: 'Distressed',
    color: 'Pattern (Camo)',
    mint: 'Vintage',
    rarity: 'Epic',
    serial: '#0044 / 600',
    lore: 'Originally a belt buckle. The blade is pinned to a denim sheath.',
    pointsBonus: 175,
    owned: false,
  },
  {
    id: 'NFT-0012',
    name: 'Void Orb',
    art: 'voidOrb',
    slot: 'item',
    fabric: 'Silk',
    fit: 'Cropped',
    finish: 'Glossy',
    color: 'Color-shifting',
    mint: 'Legendary',
    rarity: 'Legendary',
    serial: '#0002 / 30',
    lore: 'Genuine fabric, painted to look like glass. Weighs nothing.',
    pointsBonus: 250,
    owned: false,
  },
];

const RARITY_COLOR = {
  Common: 'pink',
  Rare: 'sky',
  Epic: 'lavender',
  Legendary: 'coral',
};

window.NFT_LIBRARY = NFT_LIBRARY;
window.RARITY_COLOR = RARITY_COLOR;
